image: node:latest

stages:
  - Build
  - Test
  - Deploy Staging
  - Zod
  
cache:
  paths:
    - node_modules/

Install Dependencies:
  stage: Build
  except:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - branches
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

Unit Tests:
  stage: Test
  except:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - branches
  script: yarn test

Code Coverage:
  stage: Test
  except:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - branches
  script: npm run coverage

variables:
  DATA_BUILD: data-$CI_COMMIT_SHA

Build:
  stage: Build
  except:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - branches
  script:
    - yarn build

Deploy Staging:
  type: deploy
  stage: Deploy Staging
  variables:
    DATA_BUILD: deploy/data/$CI_COMMIT_TAG
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - tags
  image: starefossen/ruby-node:latest
  script:
    - yarn build
    - mkdir -p $DATA_BUILD
    - cp -a bridge/build/data/. $DATA_BUILD
    - gem install dpl
    - dpl --skip_cleanup --provider=s3 --access_key_id=$DIGITAL_OCEAN_ACCESS_KEY_ID --secret_access_key=$DIGITAL_OCEAN_SECRET_ACCESS_KEY --bucket=xura-cdn --region=sfo2 --endpoint=https://sfo2.digitaloceanspaces.com --local_dir=./deploy --upload_dir=staging --acl=public_read

  Remove Old Deployments:
    stage: Zod
    script:
       - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PW\"}}}" > /kaniko/.docker/config.json
       - docker run -it registry.xura.io/joe307bad/scripts/v0.0.23 deploy:clean staging
    
