image: node:latest

stages:
  - Build
  - Test
  - Deploy
  
# cache:
#   paths:
#     - node_modules/

# Install Dependencies:
#   stage: Build
#   script:
#     - yarn install
#   artifacts:
#     paths:
#       - node_modules/

# Unit Tests:
#   stage: Test
#   script: yarn test

# Code Coverage:
#   stage: Test
#   script: npm run coverage

Build:
  stage: Build
  script:
    - yarn build

Deploy Staging:
  stage: Deploy
  variables:
    VERSION: data-$CI_COMMIT_SHA
  before_script:
    - ls
    - mv bridge/build /bridge/build-$VERSION
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=s3 --access_key_id=$DIGITAL_OCEAN_ACCESS_KEY_ID --secret_access_key=$DIGITAL_OCEAN_ACCESS_KEY --bucket=xura-cdn --region=sfo2 --endpoint=https://sfo2.digitaloceanspaces.com --local_dir=/bridge --upload_dir=/staging --acl=public_read
