image: node:latest

stages:
  - Troubleshooting
#   - Build
#   - Test
#   - Upload assets
#   - Zod

Troubleshooting:
  stage: Troubleshooting
  image: 
    name: xuraio/node-ansible
  script:
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - curl -s -N https://cdn.xura.io/zod/zod.tar.gz -O
    - tar -xf zod.tar.gz
    - curl -s -N -o zod/.env https://cdn.xura.io/zod/env
    - curl -s -N https://cdn.xura.io/zod/ansible.tar.gz -O
    - tar -xf ansible.tar.gz
    - mv src/core/ansible zod/lib/core/ansible
    - ls zod/lib/core
    - zod/bin/zod deploy:create $CI_COMMIT_TAG

# cache:
#   paths:
#     - node_modules/
#     - zod/

# Install Dependencies:
#   stage: Build
#   script: yarn install

# variables:
#   DATA_BUILD: data-$CI_COMMIT_SHA

# Build:
#   stage: Build
#   script: yarn build

# Unit Tests:
#   stage: Test
#   script: yarn test

# Upload assets to CDN:
#   type: deploy
#   stage: Upload assets
#   variables:
#     DATA_BUILD: deploy/data/$CI_COMMIT_TAG
#   only:
#     variables:
#       - $CI_COMMIT_REF_NAME == "master"
#   only:
#     - tags
#   image: starefossen/ruby-node:latest
#   script:
#     - yarn build
#     - mkdir -p $DATA_BUILD
#     - cp solo/index.html $DATA_BUILD
#     - cp -a bridge/build/data/. $DATA_BUILD
#     - gem install dpl
#     - dpl --skip_cleanup --provider=s3 --access_key_id=$DIGITAL_OCEAN_ACCESS_KEY_ID --secret_access_key=$DIGITAL_OCEAN_SECRET_ACCESS_KEY --bucket=xura-cdn --region=sfo2 --endpoint=https://sfo2.digitaloceanspaces.com --local_dir=./deploy --upload_dir=staging --acl=public_read

# Create Staging URL:
#   stage: Zod
#   image: 
#     name: xuraio/node-ansible
#     entrypoint: [""]
#   only:
#     variables:
#       - $CI_COMMIT_REF_NAME == "master"
#   only:
#     - tags
#   script:
#     - echo $ANSIBLE_INVENTORY
#     - echo $ANSIBLE_PRIVATE_KEY
#     - curl -s -N https://cdn.xura.io/zod/zod.tar.gz -O
#     - tar -xf zod.tar.gz
#     - curl -s -N -o zod/.env https://cdn.xura.io/zod/env
#     - zod/bin/zod deploy:create $CI_COMMIT_TAG

# Remove Old Deployments:
#   stage: Zod
#   image: 
#     name: xuraio/node-ansible
#     entrypoint: [""]
#   only:
#     variables:
#       - $CI_COMMIT_REF_NAME == "master"
#   only:
#     - tags
#   script:
#     - curl -s -N https://cdn.xura.io/zod/zod.tar.gz -O
#     - tar -xf zod.tar.gz
#     - curl -s -N -o zod/.env https://cdn.xura.io/zod/env
#     - zod/bin/zod deploy:clean staging    
