image: node:latest

stages:
  - Build
  - Test
  - Deploy
  
# cache:
#   paths:
#     - node_modules/

# Install Dependencies:
#   stage: Build
#   script:
#     - yarn install
#   artifacts:
#     paths:
#       - node_modules/

# Unit Tests:
#   stage: Test
#   script: yarn test

# Code Coverage:
#   stage: Test
#   script: npm run coverage
  
variables:
  HERMES: registry.xura.io/joe307bad/scripts:v0.0.13

Deploy:
  stage: Deploy
  image: docker:18.09.7-dind
  before_script:
    - ls /builds/$CI_PROJECT_PATH
    - docker login -u $REGISTRY_USER -p $REGISTRY_PW registry.xura.io
  script:
    - cp /builds/$CI_PROJECT_PATH/index.d.ts /src/index.d.ts
    - docker pull $HERMES
    - docker run -e NODE_ENV=production -e DIGITAL_OCEAN_ACCESS_KEY_ID=$DIGITAL_OCEAN_ACCESS_KEY_ID -e DIGITAL_OCEAN_SECRET_ACCESS_KEY=$DIGITAL_OCEAN_ACCESS_KEY -v $(pwd)/src:/src:rw $HERMES deploy --filePath /src/index.d.ts --fileName deploy-test1.txt

