image: node:latest

stages:
  - Build
  - Test
  - Deploy

# cache:
#   paths:
#     - node_modules/

# Install Dependencies:
#   stage: Build
#   script:
#     - yarn install
#   artifacts:
#     paths:
#       - node_modules/

# Unit Tests:
#   stage: Test
#   script: yarn test

# Code Coverage:
#   stage: Test
#   script: npm run coverage

variables:
  MOUNT_POINT: /builds/$CI_PROJECT_PATH

Deploy:
  stage: Deploy
  image: docker:18.09.7-dind
  environment:
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PW registry.xura.io
  script:
    - docker pull registry.xura.io/joe307bad/scripts:v0.0.13
    - docker run -e NODE_ENV=production -e DIGITAL_OCEAN_ACCESS_KEY_ID=$DIGITAL_OCEAN_ACCESS_KEY_ID -e DIGITAL_OCEAN_SECRET_ACCESS_KEY=$DIGITAL_OCEAN_ACCESS_KEY -v /$CI_PROJECT_PATH:/src registry.xura.io/joe307bad/scripts:v0.0.13 deploy --filePath /src/index.d.ts --fileName deploy-test.txt

