image: node:latest

stages:
  - Build
  - Test

cache:
  paths:
    - node_modules/

Install Dependencies:
  stage: Build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

Unit Tests:
  stage: Test
  script: yarn test

Code Coverage:
  stage: Test
  script: npm run coverage