image: node:latest

stages:
  - Build
  - Test
  - Deploy Staging
  
cache:
  paths:
    - node_modules/

Install Dependencies:
  stage: Build
  only:
    - branches
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

Unit Tests:
  stage: Test
  only:
    - branches
  script: yarn test

Code Coverage:
  stage: Test
  only:
    - branches
  script: npm run coverage

Build:
  stage: Build
  script:
    - yarn build
  artifacts:
    paths:
      - bridge/build/

Deploy Staging:
  stage: Deploy Staging
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - tags
  variables:
    VERSION: data-$CI_COMMIT_SHA
  before_script:
    - mv bridge/build bridge/build-$VERSION
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=s3 --access_key_id=$DIGITAL_OCEAN_ACCESS_KEY_ID --secret_access_key=$DIGITAL_OCEAN_SECRET_ACCESS_KEY --bucket=xura-cdn --region=sfo2 --endpoint=https://sfo2.digitaloceanspaces.com --local_dir=bridge --upload_dir=/staging --acl=public_read
